# site-wide variables
title: The Greene Lab
location: https://greenelab.com
themeColor: "#009688"
email: casey@greenelab.com
email2: greenescientist@gmail.com
github: greenelab
twitter: GreeneScientist
instagram: greenelab

# make member collection output individual page for each member
collections:
  members:
    output: true

# test with /greenelab.com appended to url for gh-pages
# (remove when we transfer site to greenelab.com)
baseurl: /greenelab.com

# default front matter parameters
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "members"
    values:
      layout: member
  -
    scope:
      type: "posts"
    values:
      layout: post

# build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
