# site-wide variables
title: The Greene Lab
location: https://greenelab.com
themeColor: "#009688"
email: casey@greenelab.com
email2: greenescientist@gmail.com
github: greenelab
twitter: GreeneScientist
instagram:  greenelab

# build settings
theme: minima
plugins:
  - jekyll-feed
