# site-wide variables
title: The Greene Lab
location: https://greenelab.com
themeColor: "#009688"
email: casey@greenelab.com
email2: greenescientist@gmail.com
github: greenelab
twitter: GreeneScientist
instagram:  greenelab

# test with /greenelab.com appended to url for gh-pages
# (remove when we transfer site to greenelab.com)
baseurl: /greenelab.com

# default front matter parameters
defaults:
  -
    scope:
      path: ""
    values:
      layout: default

# build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
