# site-wide variables
title: The Greene Lab
email: casey@greenelab.com
google: Casey Greene
github: greenelab
twitter: GreeneScientist
instagram: greenelab

# base directory where site is hosted
baseurl: ""

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      description: Where data and biology
      background: images/backgrounds/laptop-paper.jpg
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
