name: Generate citations

on:
  push:
    branches:
      - main
    paths:
      - "_data/research.yaml"
  pull_request:
    paths:
      - "_data/research.yaml"

jobs:
  update_research:
    name: Generate citations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Manubot
        run: pip install --upgrade manubot
      - name: Build updated research output file
        run: python _data/generate-citations.py
      - name: Commit new research output file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "_data/research-output.yaml"
          commit_message: "Generate citations"
          push_options: --force
